/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class FlashwindowListener */

#ifndef _Included_FlashwindowListener
#define _Included_FlashwindowListener
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     FlashwindowListener
 * Method:    flashWindow
 * Signature: (Ljava/awt/Window;)V
 */
JNIEXPORT void JNICALL Java_FlashwindowListener_flashWindow
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
